if(EXISTS "/root/.openclaw/workspace/SoftGPU/build_check/tests/stages/test_Framebuffer[1]_tests.cmake")
  include("/root/.openclaw/workspace/SoftGPU/build_check/tests/stages/test_Framebuffer[1]_tests.cmake")
else()
  add_test(test_Framebuffer_NOT_BUILT test_Framebuffer_NOT_BUILT)
endif()
