add_test([=[MathTest.Vec3BasicOperations]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.Vec3BasicOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.Vec3BasicOperations]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.Vec3Normalization]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.Vec3Normalization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.Vec3Normalization]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.Mat4Identity]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.Mat4Identity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.Mat4Identity]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.Mat4PerspectiveProjection]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.Mat4PerspectiveProjection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.Mat4PerspectiveProjection]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.Mat4Translation]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.Mat4Translation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.Mat4Translation]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.Mat4TransformChain]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.Mat4TransformChain]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.Mat4TransformChain]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.QuatBasicRotation]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.QuatBasicRotation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.QuatBasicRotation]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.QuatNormalization]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.QuatNormalization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.QuatNormalization]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.QuatToMat4]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.QuatToMat4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.QuatToMat4]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MathTest.MathConstants]=]  /root/.openclaw/workspace/SoftGPU/build_p0/bin/math_test [==[--gtest_filter=MathTest.MathConstants]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MathTest.MathConstants]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_p0/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  math_test_TESTS MathTest.Vec3BasicOperations MathTest.Vec3Normalization MathTest.Mat4Identity MathTest.Mat4PerspectiveProjection MathTest.Mat4Translation MathTest.Mat4TransformChain MathTest.QuatBasicRotation MathTest.QuatNormalization MathTest.QuatToMat4 MathTest.MathConstants)
