if(EXISTS "/root/.openclaw/workspace/SoftGPU/build_g1_tests/tests/core/math_test[1]_tests.cmake")
  include("/root/.openclaw/workspace/SoftGPU/build_g1_tests/tests/core/math_test[1]_tests.cmake")
else()
  add_test(math_test_NOT_BUILT math_test_NOT_BUILT)
endif()
