add_test([=[WindowTest.GlfwInitialized]=]  /root/.openclaw/workspace/SoftGPU/build_test2/bin/window_test [==[--gtest_filter=WindowTest.GlfwInitialized]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WindowTest.GlfwInitialized]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_test2/tests/platform SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WindowTest.CreateAndDestroyWindow]=]  /root/.openclaw/workspace/SoftGPU/build_test2/bin/window_test [==[--gtest_filter=WindowTest.CreateAndDestroyWindow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WindowTest.CreateAndDestroyWindow]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_test2/tests/platform SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WindowTest.OpenGLContextCreated]=]  /root/.openclaw/workspace/SoftGPU/build_test2/bin/window_test [==[--gtest_filter=WindowTest.OpenGLContextCreated]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WindowTest.OpenGLContextCreated]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_test2/tests/platform SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WindowTest.WindowResize]=]  /root/.openclaw/workspace/SoftGPU/build_test2/bin/window_test [==[--gtest_filter=WindowTest.WindowResize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WindowTest.WindowResize]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_test2/tests/platform SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WindowTest.SwapInterval]=]  /root/.openclaw/workspace/SoftGPU/build_test2/bin/window_test [==[--gtest_filter=WindowTest.SwapInterval]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WindowTest.SwapInterval]=]  PROPERTIES WORKING_DIRECTORY /root/.openclaw/workspace/SoftGPU/build_test2/tests/platform SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  window_test_TESTS WindowTest.GlfwInitialized WindowTest.CreateAndDestroyWindow WindowTest.OpenGLContextCreated WindowTest.WindowResize WindowTest.SwapInterval)
