if(EXISTS "/root/.openclaw/workspace/SoftGPU/build_asan/tests/core/test_memory[1]_tests.cmake")
  include("/root/.openclaw/workspace/SoftGPU/build_asan/tests/core/test_memory[1]_tests.cmake")
else()
  add_test(test_memory_NOT_BUILT test_memory_NOT_BUILT)
endif()
