if(EXISTS "/root/.openclaw/workspace/SoftGPU/build_test/tests/stages/test_PrimitiveAssembly[1]_tests.cmake")
  include("/root/.openclaw/workspace/SoftGPU/build_test/tests/stages/test_PrimitiveAssembly[1]_tests.cmake")
else()
  add_test(test_PrimitiveAssembly_NOT_BUILT test_PrimitiveAssembly_NOT_BUILT)
endif()
