if(EXISTS "/root/.openclaw/workspace/SoftGPU/build_quick/tests/stages/test_Integration[1]_tests.cmake")
  include("/root/.openclaw/workspace/SoftGPU/build_quick/tests/stages/test_Integration[1]_tests.cmake")
else()
  add_test(test_Integration_NOT_BUILT test_Integration_NOT_BUILT)
endif()
